runtime: nodejs16 # or another supported version

instance_class: F1

service: frontend

env_variables:
  PUBLIC_API: https://trans-radius-98822.appspot.com

handlers:

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto