name: Frontend Workflow

on:
  push:
    branches:
      - master
      - feature-update-frontend
    paths:
      - '.github/workflows/frontend.yaml'
      - 'frontend/**'
  workflow_dispatch: {}

jobs:
  Frontend:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: access_token
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GOOGLE_IDENTITY_PROVIDER }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      
      - name: Get tag
        id: get-tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./frontend/Dockerfile
          context: ./frontend
          tags: us-east4-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_PROD }}/docker/frontend:${{ steps.get-tag.outputs.sha_short }}
      
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'frontend'
          image: us-east4-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_PROD }}/docker/frontend:${{ steps.get-tag.outputs.sha_short }}
          flags: --service-account=${{ secrets.FRONTEND_SERVICE_ACCOUNT }} --allow-unauthenticated
          env_vars: |-
            BACKEND_URL=${{ secrets.BACKEND_URL }}
